# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simul <- function(df, ids, nums, ls) {
    .Call(`_projmanr_simul`, df, ids, nums, ls)
}
